### ISSUE TITLE
Use of Raw AQL Queries

### ISSUE THREAD

**Issue by tbm206** [ArangoDB-Community/arangodb_ecto#15]
First, thank you for maintaining this driver.

I'm new to Elixir/Phoenix (currently using NodeJs) and considering migrating to Elixir.

The ArangoDB JavaScript driver API allows to write raw AQL queries. Does this driver allow to write raw AQL queries? If so, is there a documentation on this?

**Comment by mpoeter** [comment]
If you use Ecto it is generally better/easier to use the built-in DSL based queries. However, there are limitations to what you can express in these queries. If you find yourself in a situation where the Ecto queries are too limited, you can resort to raw AQL queries like this:
```
ArangoDB.Ecto.query(MyRepo, "<raw AQL>")
```

**Comment by tbm206** [comment]
Thanks @mpoeter. That's very helpful.

Since I haven't settled on a particular language/framework, I prefer to keep the AQL query in raw form.

But I sure will use Ecto's DSL where appropriate.
